name: Build AppImage

on:
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - uses: pkgforge-dev/anylinux-setup-action@v2
      - name: Install dependencies
        run: /bin/sh ./appimage/get-dependencies.sh
      - name: Make AppImage
        run: /bin/sh ./appimage/make-appimage.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppImage-${{ matrix.arch }}
          path: dist

  release:
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: AppImage-*
          merge-multiple: true
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for f in *.AppImage *.AppImage.zsync; do
            [ -f "$f" ] && gh release upload "${{ github.event.release.tag_name }}" "$f" --clobber
          done
